// stash/unused-frontend/src/components/admin/AdminLayout.tsx

import { Link, Outlet } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import { Navigate } from 'react-router-dom';

export default function AdminLayout() {
  const { profile, loading } = useAuth();

  if (loading) {
    return <div>Loading...</div>;
  }

  if (!profile?.is_admin) {
    return <Navigate to="/en/home" replace />;
  }

  return (
    <div className="flex h-screen bg-gray-100">
      {/* Sidebar */}
      <aside className="w-64 flex-shrink-0 bg-gray-800 text-white flex flex-col">
        <div className="h-16 flex items-center justify-center px-4 bg-gray-900 flex-shrink-0">
          <Link to="/admin/dashboard" className="font-semibold text-lg">Admin Panel</Link>
        </div>
        <nav className="flex-1 overflow-y-auto">
          <ul className="py-4">
            <li><Link to="/admin/dashboard" className="block px-4 py-2 hover:bg-gray-700">Dashboard</Link></li>
            <li><Link to="/admin/users" className="block px-4 py-2 hover:bg-gray-700">User Management</Link></li>
            <li><Link to="/admin/daily-orders" className="block px-4 py-2 hover:bg-gray-700">Daily Orders</Link></li>
            <li><Link to="/admin/menu-scheduler" className="block px-4 py-2 hover:bg-gray-700">Menu Scheduler</Link></li>
            <li><Link to="/admin/meals" className="block px-4 py-2 hover:bg-gray-700">Meal Management</Link></li>
            <li><Link to="/admin/plans" className="block px-4 py-2 hover:bg-gray-700">Plan Management</Link></li>
          </ul>
        </nav>
      </aside>

      {/* Main content */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-100 p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
}

// src/components/admin/admin-layout/admin-layout.component.ts

import { Component, ChangeDetectionStrategy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-admin-layout',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './admin-layout.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AdminLayoutComponent {
  isSidebarOpen = signal(true);

  toggleSidebar() {
    this.isSidebarOpen.update(v => !v);
  }
}


<div class="flex h-screen bg-gray-100">
  <!-- Sidebar -->
  <aside class="w-64 flex-shrink-0 bg-gray-800 text-white flex flex-col transition-all duration-300" [class.w-20]="!isSidebarOpen()">
    <div class="h-16 flex items-center justify-between px-4 bg-gray-900 flex-shrink-0">
       <a routerLink="/admin" class="flex items-center gap-2" [class.hidden]="!isSidebarOpen()">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-7 h-7 text-red-400">
            <path fill-rule="evenodd" d="M12 1.5a5.25 5.25 0 00-5.25 5.25v3a3 3 0 00-3 3v6.75a3 3 0 003 3h10.5a3 3 0 003-3v-6.75a3 3 0 00-3-3v-3A5.25 5.25 0 0012 1.5zm-3.75 5.25a3.75 3.75 0 107.5 0v3h-7.5v-3z" clip-rule="evenodd" />
          </svg>
          <span class="font-semibold text-lg">Admin Panel</span>
        </a>
      <button (click)="toggleSidebar()" class="p-2 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-white">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
        </svg>
      </button>
    </div>
    <nav class="flex-1 overflow-y-auto">
      <ul class="py-4">
        <li>
          <a routerLink="dashboard" routerLinkActive="bg-gray-700" class="flex items-center px-4 py-3 text-gray-300 hover:bg-gray-700">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6"><path fill-rule="evenodd" d="M3 6a3 3 0 013-3h12a3 3 0 013 3v12a3 3 0 01-3 3H6a3 3 0 01-3-3V6zm4.5 9a1.5 1.5 0 100-3 1.5 1.5 0 000 3zM12 15a1.5 1.5 0 100-3 1.5 1.5 0 000 3zm4.5 0a1.5 1.5 0 100-3 1.5 1.5 0 000 3zm-9-4.5a1.5 1.5 0 100-3 1.5 1.5 0 000 3z" clip-rule="evenodd" /></svg>
            <span class="ml-3" [class.hidden]="!isSidebarOpen()">Dashboard</span>
          </a>
        </li>
        <li>
          <a routerLink="users" routerLinkActive="bg-gray-700" class="flex items-center px-4 py-3 text-gray-300 hover:bg-gray-700">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6"><path d="M4.5 6.375a4.125 4.125 0 118.25 0 4.125 4.125 0 01-8.25 0zM14.25 8.625a3.375 3.375 0 116.75 0 3.375 3.375 0 01-6.75 0zM4.5 16.125a3.375 3.375 0 116.75 0 3.375 3.375 0 01-6.75 0zM14.25 16.125a4.125 4.125 0 118.25 0 4.125 4.125 0 01-8.25 0z" /></svg>
            <span class="ml-3" [class.hidden]="!isSidebarOpen()">User Management</span>
          </a>
        </li>
        <li>
          <a routerLink="daily-orders" routerLinkActive="bg-gray-700" class="flex items-center px-4 py-3 text-gray-300 hover:bg-gray-700">
             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6"><path fill-rule="evenodd" d="M4.848 2.771A49.144 49.144 0 0112 2.25c2.43 0 4.817.178 7.152.52 1.978.292 3.348 2.024 3.348 3.97v6.02c0 1.946-1.37 3.678-3.348 3.97a48.901 48.901 0 01-3.476.383.39.39 0 00-.297.17l-2.755 4.133a.75.75 0 01-1.248 0l-2.755-4.133a.39.39 0 00-.297-.17 48.9 48.9 0 01-3.476-.384c-1.978-.29-3.348-2.024-3.348-3.97V6.741c0-1.946 1.37-3.68 3.348-3.97zM6.75 8.25a.75.75 0 01.75-.75h9a.75.75 0 010 1.5h-9a.75.75 0 01-.75-.75zm.75 2.25a.75.75 0 000 1.5H12a.75.75 0 000-1.5H7.5z" clip-rule="evenodd" /></svg>
             <span class="ml-3" [class.hidden]="!isSidebarOpen()">Daily Orders</span>
          </a>
        </li>
        <li>
          <a routerLink="menu-scheduler" routerLinkActive="bg-gray-700" class="flex items-center px-4 py-3 text-gray-300 hover:bg-gray-700">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6"><path fill-rule="evenodd" d="M6.75 2.25A.75.75 0 017.5 3v1.5h9V3A.75.75 0 0118 3v1.5h.75a3 3 0 013 3v11.25a3 3 0 01-3 3H5.25a3 3 0 01-3-3V7.5a3 3 0 013-3H6V3a.75.75 0 01.75-.75zM5.25 6.75c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h13.5c.621 0 1.125-.504 1.125-1.125V7.875c0-.621-.504-1.125-1.125-1.125H5.25z" clip-rule="evenodd" /></svg>
            <span class="ml-3" [class.hidden]="!isSidebarOpen()">Menu Scheduler</span>
          </a>
        </li>
        <li>
          <a routerLink="meals" routerLinkActive="bg-gray-700" class="flex items-center px-4 py-3 text-gray-300 hover:bg-gray-700">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6"><path d="M11.25 4.533A9.708 9.708 0 0012 4.5c4.418 0 8.25 2.533 9.75 6.166A9.75 9.75 0 0112 21c-4.418 0-8.25-2.533-9.75-6.167A9.75 9.75 0 0111.25 4.533zM12 7.5a4.5 4.5 0 100 9 4.5 4.5 0 000-9z" /></svg>
            <span class="ml-3" [class.hidden]="!isSidebarOpen()">Meal Management</span>
          </a>
        </li>
        <li>
          <a routerLink="plans" routerLinkActive="bg-gray-700" class="flex items-center px-4 py-3 text-gray-300 hover:bg-gray-700">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6"><path d="M12 7.5a2.25 2.25 0 100 4.5 2.25 2.25 0 000-4.5z" /><path fill-rule="evenodd" d="M1.5 4.875C1.5 3.839 2.34 3 3.375 3h17.25c1.035 0 1.875.84 1.875 1.875v9.75c0 1.036-.84 1.875-1.875 1.875H3.375A1.875 1.875 0 011.5 14.625v-9.75zM8.25 9.75a3.75 3.75 0 117.5 0 3.75 3.75 0 01-7.5 0zM18.75 9a.75.75 0 00-.75.75v.008c0 .414.336.75.75.75h.008a.75.75 0 00.75-.75v-.008a.75.75 0 00-.75-.75h-.008zM4.5 9.75A.75.75 0 015.25 9h.008a.75.75 0 01.75.75v.008a.75.75 0 01-.75.75H5.25a.75.75 0 01-.75-.75V9.75z" clip-rule="evenodd" /></svg>
            <span class="ml-3" [class.hidden]="!isSidebarOpen()">Plan Management</span>
          </a>
        </li>
      </ul>
    </nav>
  </aside>

  <!-- Main content -->
  <div class="flex-1 flex flex-col overflow-hidden">
    <!-- Header -->
    <header class="bg-white shadow-sm h-16 flex items-center justify-between px-6 flex-shrink-0">
        <h1 class="text-xl font-semibold text-gray-800">Admin Dashboard</h1>
        <a routerLink="/" class="text-sm font-medium text-red-600 hover:text-red-800">Back to Main Site &rarr;</a>
    </header>
    <!-- Content area -->
    <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-100">
      <div class="container mx-auto px-6 py-8">
        <router-outlet></router-outlet>
      </div>
    </main>
  </div>
</div>
